//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GAPPSF.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GAPPSF.Resources.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account name.
        /// </summary>
        internal static string AccountName {
            get {
                return ResourceManager.GetString("AccountName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accounts.
        /// </summary>
        internal static string Accounts {
            get {
                return ResourceManager.GetString("Accounts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Action.
        /// </summary>
        internal static string Action {
            get {
                return ResourceManager.GetString("Action", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Action Builder.
        /// </summary>
        internal static string ActionBuilder {
            get {
                return ResourceManager.GetString("ActionBuilder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Active.
        /// </summary>
        internal static string Active {
            get {
                return ResourceManager.GetString("Active", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        internal static string Add {
            get {
                return ResourceManager.GetString("Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add additional waypoints to description.
        /// </summary>
        internal static string AddAdditionWaypointsToDescription {
            get {
                return ResourceManager.GetString("AddAdditionWaypointsToDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.Coords.
        /// </summary>
        internal static string AddCoords {
            get {
                return ResourceManager.GetString("AddCoords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Include notes in description.
        /// </summary>
        internal static string AddFieldnotesToDescription {
            get {
                return ResourceManager.GetString("AddFieldnotesToDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add to current selection.
        /// </summary>
        internal static string AddToSelection {
            get {
                return ResourceManager.GetString("AddToSelection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All.
        /// </summary>
        internal static string All {
            get {
                return ResourceManager.GetString("All", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alt.
        /// </summary>
        internal static string Alt {
            get {
                return ResourceManager.GetString("Alt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application info.
        /// </summary>
        internal static string ApplicationInfo {
            get {
                return ResourceManager.GetString("ApplicationInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Archived.
        /// </summary>
        internal static string Archived {
            get {
                return ResourceManager.GetString("Archived", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Area.
        /// </summary>
        internal static string Area {
            get {
                return ResourceManager.GetString("Area", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to At least one user.
        /// </summary>
        internal static string AtLeastOneUser {
            get {
                return ResourceManager.GetString("AtLeastOneUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attributes.
        /// </summary>
        internal static string Attributes {
            get {
                return ResourceManager.GetString("Attributes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Authorize.
        /// </summary>
        internal static string Authorize {
            get {
                return ResourceManager.GetString("Authorize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Authorized.
        /// </summary>
        internal static string Authorized {
            get {
                return ResourceManager.GetString("Authorized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Automatic select new geocaches.
        /// </summary>
        internal static string AutomaticSelectNewGeocaches {
            get {
                return ResourceManager.GetString("AutomaticSelectNewGeocaches", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Available.
        /// </summary>
        internal static string Available {
            get {
                return ResourceManager.GetString("Available", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Buffer level.
        /// </summary>
        internal static string BufferLevel {
            get {
                return ResourceManager.GetString("BufferLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to By.
        /// </summary>
        internal static string By {
            get {
                return ResourceManager.GetString("By", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cache list.
        /// </summary>
        internal static string CacheList {
            get {
                return ResourceManager.GetString("CacheList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cache type.
        /// </summary>
        internal static string CacheType {
            get {
                return ResourceManager.GetString("CacheType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Center.
        /// </summary>
        internal static string Center {
            get {
                return ResourceManager.GetString("Center", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Center coordinates.
        /// </summary>
        internal static string CenterCoordinates {
            get {
                return ResourceManager.GetString("CenterCoordinates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to City.
        /// </summary>
        internal static string City {
            get {
                return ResourceManager.GetString("City", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to City / coordinates.
        /// </summary>
        internal static string CityCoordinate {
            get {
                return ResourceManager.GetString("CityCoordinate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear.
        /// </summary>
        internal static string Clear {
            get {
                return ResourceManager.GetString("Clear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear all filters.
        /// </summary>
        internal static string ClearAllFilters {
            get {
                return ResourceManager.GetString("ClearAllFilters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear selection.
        /// </summary>
        internal static string ClearSelection {
            get {
                return ResourceManager.GetString("ClearSelection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cluster Marker.
        /// </summary>
        internal static string ClusterMarker {
            get {
                return ResourceManager.GetString("ClusterMarker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Code.
        /// </summary>
        internal static string Code {
            get {
                return ResourceManager.GetString("Code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Colors.
        /// </summary>
        internal static string Colors {
            get {
                return ResourceManager.GetString("Colors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comma separated.
        /// </summary>
        internal static string CommaSeparated {
            get {
                return ResourceManager.GetString("CommaSeparated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Container.
        /// </summary>
        internal static string Container {
            get {
                return ResourceManager.GetString("Container", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contains all selected.
        /// </summary>
        internal static string ContainsAllSelected {
            get {
                return ResourceManager.GetString("ContainsAllSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contains one of selected.
        /// </summary>
        internal static string ContainsOneOfSelected {
            get {
                return ResourceManager.GetString("ContainsOneOfSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Control.
        /// </summary>
        internal static string Control {
            get {
                return ResourceManager.GetString("Control", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Coordinates.
        /// </summary>
        internal static string Coordinates {
            get {
                return ResourceManager.GetString("Coordinates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy.
        /// </summary>
        internal static string Copy {
            get {
                return ResourceManager.GetString("Copy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copying file to device.
        /// </summary>
        internal static string CopyingFileToDevice {
            get {
                return ResourceManager.GetString("CopyingFileToDevice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copying geocaches.
        /// </summary>
        internal static string CopyingGeocaches {
            get {
                return ResourceManager.GetString("CopyingGeocaches", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy selection.
        /// </summary>
        internal static string CopySelection {
            get {
                return ResourceManager.GetString("CopySelection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Country.
        /// </summary>
        internal static string Country {
            get {
                return ResourceManager.GetString("Country", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Country / State.
        /// </summary>
        internal static string CountryState {
            get {
                return ResourceManager.GetString("CountryState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create GGZ file.
        /// </summary>
        internal static string CreateGGZFile {
            get {
                return ResourceManager.GetString("CreateGGZFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creating file.
        /// </summary>
        internal static string CreatingFile {
            get {
                return ResourceManager.GetString("CreatingFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to D.
        /// </summary>
        internal static string D {
            get {
                return ResourceManager.GetString("D", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date of data.
        /// </summary>
        internal static string DateOfData {
            get {
                return ResourceManager.GetString("DateOfData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log viewer.
        /// </summary>
        internal static string DebugLogView {
            get {
                return ResourceManager.GetString("DebugLogView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        internal static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete selection.
        /// </summary>
        internal static string DeleteSelection {
            get {
                return ResourceManager.GetString("DeleteSelection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deleting geocaches.
        /// </summary>
        internal static string DeletingGeocaches {
            get {
                return ResourceManager.GetString("DeletingGeocaches", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Diff.
        /// </summary>
        internal static string Diff {
            get {
                return ResourceManager.GetString("Diff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Difficulty.
        /// </summary>
        internal static string Difficulty {
            get {
                return ResourceManager.GetString("Difficulty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disabled.
        /// </summary>
        internal static string Disabled {
            get {
                return ResourceManager.GetString("Disabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download images for active geocache.
        /// </summary>
        internal static string DownloadImagesForActiveGeocache {
            get {
                return ResourceManager.GetString("DownloadImagesForActiveGeocache", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download images for selection.
        /// </summary>
        internal static string DownloadImagesForSelection {
            get {
                return ResourceManager.GetString("DownloadImagesForSelection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Downloading images.
        /// </summary>
        internal static string DownloadingImages {
            get {
                return ResourceManager.GetString("DownloadingImages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nederlands.
        /// </summary>
        internal static string Dutch {
            get {
                return ResourceManager.GetString("Dutch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        internal static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable above # geocaches.
        /// </summary>
        internal static string EnableAboveCountGeocaches {
            get {
                return ResourceManager.GetString("EnableAboveCountGeocaches", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enabled.
        /// </summary>
        internal static string Enabled {
            get {
                return ResourceManager.GetString("Enabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English.
        /// </summary>
        internal static string English {
            get {
                return ResourceManager.GetString("English", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export.
        /// </summary>
        internal static string Export {
            get {
                return ResourceManager.GetString("Export", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export GPX.
        /// </summary>
        internal static string ExportGPX {
            get {
                return ResourceManager.GetString("ExportGPX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export iGeoKnife.
        /// </summary>
        internal static string ExportiGeoKnife {
            get {
                return ResourceManager.GetString("ExportiGeoKnife", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exporting GPX.
        /// </summary>
        internal static string ExportingGPX {
            get {
                return ResourceManager.GetString("ExportingGPX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exporting iGeoKnife.
        /// </summary>
        internal static string ExportingiGeoKnife {
            get {
                return ResourceManager.GetString("ExportingiGeoKnife", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exporting KML.
        /// </summary>
        internal static string ExportingKML {
            get {
                return ResourceManager.GetString("ExportingKML", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exporting OV2.
        /// </summary>
        internal static string ExportingOV2 {
            get {
                return ResourceManager.GetString("ExportingOV2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export KML.
        /// </summary>
        internal static string ExportKML {
            get {
                return ResourceManager.GetString("ExportKML", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export OV2.
        /// </summary>
        internal static string ExportOV2 {
            get {
                return ResourceManager.GetString("ExportOV2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extra coord. name prefix.
        /// </summary>
        internal static string ExtraCoordPrefix {
            get {
                return ResourceManager.GetString("ExtraCoordPrefix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to F.
        /// </summary>
        internal static string F {
            get {
                return ResourceManager.GetString("F", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fav..
        /// </summary>
        internal static string Fav {
            get {
                return ResourceManager.GetString("Fav", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Favorites.
        /// </summary>
        internal static string Favorites {
            get {
                return ResourceManager.GetString("Favorites", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Feature.
        /// </summary>
        internal static string Feature {
            get {
                return ResourceManager.GetString("Feature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fields.
        /// </summary>
        internal static string Fields {
            get {
                return ResourceManager.GetString("Fields", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File.
        /// </summary>
        internal static string File {
            get {
                return ResourceManager.GetString("File", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FileName.
        /// </summary>
        internal static string FileName {
            get {
                return ResourceManager.GetString("FileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filter.
        /// </summary>
        internal static string Filter {
            get {
                return ResourceManager.GetString("Filter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New filters only apply for new imports.
        /// </summary>
        internal static string FilterApplyNote {
            get {
                return ResourceManager.GetString("FilterApplyNote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Found.
        /// </summary>
        internal static string Found {
            get {
                return ResourceManager.GetString("Found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Found by.
        /// </summary>
        internal static string FoundBy {
            get {
                return ResourceManager.GetString("FoundBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Found by all.
        /// </summary>
        internal static string FoundByAll {
            get {
                return ResourceManager.GetString("FoundByAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Freeze columns.
        /// </summary>
        internal static string FreezeColumns {
            get {
                return ResourceManager.GetString("FreezeColumns", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Français.
        /// </summary>
        internal static string French {
            get {
                return ResourceManager.GetString("French", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to From.
        /// </summary>
        internal static string From {
            get {
                return ResourceManager.GetString("From", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to From center location.
        /// </summary>
        internal static string FromCenterLocation {
            get {
                return ResourceManager.GetString("FromCenterLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to From home location.
        /// </summary>
        internal static string FromHomeLocation {
            get {
                return ResourceManager.GetString("FromHomeLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GAPP Data Storage.
        /// </summary>
        internal static string GAPPDataStorage {
            get {
                return ResourceManager.GetString("GAPPDataStorage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Geocache container.
        /// </summary>
        internal static string GeocacheContainer {
            get {
                return ResourceManager.GetString("GeocacheContainer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Geocache filter.
        /// </summary>
        internal static string GeocacheFilter {
            get {
                return ResourceManager.GetString("GeocacheFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Geocache images.
        /// </summary>
        internal static string GeocacheImages {
            get {
                return ResourceManager.GetString("GeocacheImages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Globalcaching Application is Geocaching Live Enabled.
        ///
        ///With the Geocaching Live API from Groundspeak it becomes easy to obtain data from geocaching.com and e.g. log a geocache without the need to go to the website of geocaching.com.
        ///Pocket Queries can be downloaded right from the application itself and geocaches can be updated instantly.
        ///
        ///In order to use these features, you have to authorize this application to access your account on geocaching.com..
        /// </summary>
        internal static string GeocacheLiveText {
            get {
                return ResourceManager.GetString("GeocacheLiveText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Geocaches.
        /// </summary>
        internal static string Geocaches {
            get {
                return ResourceManager.GetString("Geocaches", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Geocache type.
        /// </summary>
        internal static string GeocacheType {
            get {
                return ResourceManager.GetString("GeocacheType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Geocache viewer.
        /// </summary>
        internal static string GeocacheViewer {
            get {
                return ResourceManager.GetString("GeocacheViewer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Geocaching Live.
        /// </summary>
        internal static string GeocachingLive {
            get {
                return ResourceManager.GetString("GeocachingLive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deutsch.
        /// </summary>
        internal static string German {
            get {
                return ResourceManager.GetString("German", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get location.
        /// </summary>
        internal static string GetLocation {
            get {
                return ResourceManager.GetString("GetLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Go.
        /// </summary>
        internal static string Go {
            get {
                return ResourceManager.GetString("Go", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Google map.
        /// </summary>
        internal static string GoogleMap {
            get {
                return ResourceManager.GetString("GoogleMap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GPX.
        /// </summary>
        internal static string GPX {
            get {
                return ResourceManager.GetString("GPX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GPX version.
        /// </summary>
        internal static string GPXVersion {
            get {
                return ResourceManager.GetString("GPXVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grid size.
        /// </summary>
        internal static string GridSize {
            get {
                return ResourceManager.GetString("GridSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Help.
        /// </summary>
        internal static string Help {
            get {
                return ResourceManager.GetString("Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hints.
        /// </summary>
        internal static string Hints {
            get {
                return ResourceManager.GetString("Hints", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        internal static string Home {
            get {
                return ResourceManager.GetString("Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home coordinates.
        /// </summary>
        internal static string HomeCoordinates {
            get {
                return ResourceManager.GetString("HomeCoordinates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home location.
        /// </summary>
        internal static string HomeLocation {
            get {
                return ResourceManager.GetString("HomeLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I do not own.
        /// </summary>
        internal static string IDontOwn {
            get {
                return ResourceManager.GetString("IDontOwn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I found.
        /// </summary>
        internal static string IFound {
            get {
                return ResourceManager.GetString("IFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ignore geocaches.
        /// </summary>
        internal static string IgnoreGeocaches {
            get {
                return ResourceManager.GetString("IgnoreGeocaches", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I have not found.
        /// </summary>
        internal static string IHaveNotFound {
            get {
                return ResourceManager.GetString("IHaveNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import.
        /// </summary>
        internal static string Import {
            get {
                return ResourceManager.GetString("Import", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import GSAK database.
        /// </summary>
        internal static string ImportGSAKDatabase {
            get {
                return ResourceManager.GetString("ImportGSAKDatabase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Importing.
        /// </summary>
        internal static string Importing {
            get {
                return ResourceManager.GetString("Importing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Importing geocache images.
        /// </summary>
        internal static string ImportingGeocacheImages {
            get {
                return ResourceManager.GetString("ImportingGeocacheImages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Importing geocaches.
        /// </summary>
        internal static string ImportingGeocaches {
            get {
                return ResourceManager.GetString("ImportingGeocaches", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Importing log images.
        /// </summary>
        internal static string ImportingLogImages {
            get {
                return ResourceManager.GetString("ImportingLogImages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Importing logs.
        /// </summary>
        internal static string ImportingLogs {
            get {
                return ResourceManager.GetString("ImportingLogs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Importing user waypoints.
        /// </summary>
        internal static string ImportingUserWaypoints {
            get {
                return ResourceManager.GetString("ImportingUserWaypoints", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Importing waypoints.
        /// </summary>
        internal static string ImportingWaypoints {
            get {
                return ResourceManager.GetString("ImportingWaypoints", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add waypoints.
        /// </summary>
        internal static string IncludeChildWaypoints {
            get {
                return ResourceManager.GetString("IncludeChildWaypoints", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invert selection.
        /// </summary>
        internal static string InvertSelection {
            get {
                return ResourceManager.GetString("InvertSelection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I own.
        /// </summary>
        internal static string IOwn {
            get {
                return ResourceManager.GetString("IOwn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Key.
        /// </summary>
        internal static string Key {
            get {
                return ResourceManager.GetString("Key", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Km.
        /// </summary>
        internal static string Km {
            get {
                return ResourceManager.GetString("Km", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        internal static string Language {
            get {
                return ResourceManager.GetString("Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Level.
        /// </summary>
        internal static string Level {
            get {
                return ResourceManager.GetString("Level", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LiveAPI.
        /// </summary>
        internal static string LiveAPI {
            get {
                return ResourceManager.GetString("LiveAPI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load at startup.
        /// </summary>
        internal static string LoadAtStartup {
            get {
                return ResourceManager.GetString("LoadAtStartup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading.
        /// </summary>
        internal static string Loading {
            get {
                return ResourceManager.GetString("Loading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading database.
        /// </summary>
        internal static string LoadingDatabase {
            get {
                return ResourceManager.GetString("LoadingDatabase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading databases.
        /// </summary>
        internal static string LoadingDatabases {
            get {
                return ResourceManager.GetString("LoadingDatabases", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Location.
        /// </summary>
        internal static string Location {
            get {
                return ResourceManager.GetString("Location", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Locations.
        /// </summary>
        internal static string Locations {
            get {
                return ResourceManager.GetString("Locations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Locked.
        /// </summary>
        internal static string Locked {
            get {
                return ResourceManager.GetString("Locked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log images.
        /// </summary>
        internal static string LogImages {
            get {
                return ResourceManager.GetString("LogImages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logs.
        /// </summary>
        internal static string Logs {
            get {
                return ResourceManager.GetString("Logs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Globalcaching Application.
        /// </summary>
        internal static string MainWindowTitle {
            get {
                return ResourceManager.GetString("MainWindowTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Map.
        /// </summary>
        internal static string Map {
            get {
                return ResourceManager.GetString("Map", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maps.
        /// </summary>
        internal static string Maps {
            get {
                return ResourceManager.GetString("Maps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maximum number of logs.
        /// </summary>
        internal static string MaximumNumberOfLogs {
            get {
                return ResourceManager.GetString("MaximumNumberOfLogs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maximum zoom level.
        /// </summary>
        internal static string MaximumZoomLevel {
            get {
                return ResourceManager.GetString("MaximumZoomLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to maximum logs.
        /// </summary>
        internal static string MaxLogCount {
            get {
                return ResourceManager.GetString("MaxLogCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maximum geocache name length.
        /// </summary>
        internal static string MaxNameLength {
            get {
                return ResourceManager.GetString("MaxNameLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Membership.
        /// </summary>
        internal static string Membership {
            get {
                return ResourceManager.GetString("Membership", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Miles.
        /// </summary>
        internal static string Miles {
            get {
                return ResourceManager.GetString("Miles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minimum start of name length.
        /// </summary>
        internal static string MinStartOfname {
            get {
                return ResourceManager.GetString("MinStartOfname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Municipality.
        /// </summary>
        internal static string Municipality {
            get {
                return ResourceManager.GetString("Municipality", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Municipality / City.
        /// </summary>
        internal static string MunicipalityCity {
            get {
                return ResourceManager.GetString("MunicipalityCity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New.
        /// </summary>
        internal static string New {
            get {
                return ResourceManager.GetString("New", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New search.
        /// </summary>
        internal static string NewSelection {
            get {
                return ResourceManager.GetString("NewSelection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        internal static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No geocache selected.
        /// </summary>
        internal static string NoGeocacheSelected {
            get {
                return ResourceManager.GetString("NoGeocacheSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to None of selected.
        /// </summary>
        internal static string NoneOfSelected {
            get {
                return ResourceManager.GetString("NoneOfSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Note.
        /// </summary>
        internal static string Note {
            get {
                return ResourceManager.GetString("Note", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not found by.
        /// </summary>
        internal static string NotFoundBy {
            get {
                return ResourceManager.GetString("NotFoundBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not found by any.
        /// </summary>
        internal static string NotFoundByAny {
            get {
                return ResourceManager.GetString("NotFoundByAny", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Offline images.
        /// </summary>
        internal static string OfflineImages {
            get {
                return ResourceManager.GetString("OfflineImages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        internal static string OK {
            get {
                return ResourceManager.GetString("OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OKAPI.
        /// </summary>
        internal static string OKAPI {
            get {
                return ResourceManager.GetString("OKAPI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open.
        /// </summary>
        internal static string Open {
            get {
                return ResourceManager.GetString("Open", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Original text.
        /// </summary>
        internal static string OriginalText {
            get {
                return ResourceManager.GetString("OriginalText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Own.
        /// </summary>
        internal static string Own {
            get {
                return ResourceManager.GetString("Own", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Owner.
        /// </summary>
        internal static string Owner {
            get {
                return ResourceManager.GetString("Owner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paste.
        /// </summary>
        internal static string Paste {
            get {
                return ResourceManager.GetString("Paste", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paste selection.
        /// </summary>
        internal static string PasteSelection {
            get {
                return ResourceManager.GetString("PasteSelection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Personal notes.
        /// </summary>
        internal static string PersonalNotes {
            get {
                return ResourceManager.GetString("PersonalNotes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PMO.
        /// </summary>
        internal static string PMO {
            get {
                return ResourceManager.GetString("PMO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prefix.
        /// </summary>
        internal static string Prefix {
            get {
                return ResourceManager.GetString("Prefix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Property.
        /// </summary>
        internal static string Property {
            get {
                return ResourceManager.GetString("Property", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Publication date.
        /// </summary>
        internal static string PublicationDate {
            get {
                return ResourceManager.GetString("PublicationDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Published.
        /// </summary>
        internal static string Published {
            get {
                return ResourceManager.GetString("Published", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quick select.
        /// </summary>
        internal static string QuickSelect {
            get {
                return ResourceManager.GetString("QuickSelect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Radius.
        /// </summary>
        internal static string Radius {
            get {
                return ResourceManager.GetString("Radius", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove.
        /// </summary>
        internal static string Remove {
            get {
                return ResourceManager.GetString("Remove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to S.
        /// </summary>
        internal static string S {
            get {
                return ResourceManager.GetString("S", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saving.
        /// </summary>
        internal static string Saving {
            get {
                return ResourceManager.GetString("Saving", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saving data.
        /// </summary>
        internal static string SavingData {
            get {
                return ResourceManager.GetString("SavingData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saving geocaches.
        /// </summary>
        internal static string SavingGeocaches {
            get {
                return ResourceManager.GetString("SavingGeocaches", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        internal static string Search {
            get {
                return ResourceManager.GetString("Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Searching.
        /// </summary>
        internal static string Searching {
            get {
                return ResourceManager.GetString("Searching", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select.
        /// </summary>
        internal static string Select {
            get {
                return ResourceManager.GetString("Select", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select all.
        /// </summary>
        internal static string SelectAll {
            get {
                return ResourceManager.GetString("SelectAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select archived.
        /// </summary>
        internal static string SelectArchived {
            get {
                return ResourceManager.GetString("SelectArchived", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select available.
        /// </summary>
        internal static string SelectAvailable {
            get {
                return ResourceManager.GetString("SelectAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select with corrected coords.
        /// </summary>
        internal static string SelectCorrectCoords {
            get {
                return ResourceManager.GetString("SelectCorrectCoords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selected.
        /// </summary>
        internal static string Selected {
            get {
                return ResourceManager.GetString("Selected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select flagged.
        /// </summary>
        internal static string SelectFlagged {
            get {
                return ResourceManager.GetString("SelectFlagged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select found.
        /// </summary>
        internal static string SelectFound {
            get {
                return ResourceManager.GetString("SelectFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Caches with multiple founds.
        /// </summary>
        internal static string SelectMultipleFounds {
            get {
                return ResourceManager.GetString("SelectMultipleFounds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select notes.
        /// </summary>
        internal static string SelectNotes {
            get {
                return ResourceManager.GetString("SelectNotes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select not found.
        /// </summary>
        internal static string SelectNotFound {
            get {
                return ResourceManager.GetString("SelectNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select you own.
        /// </summary>
        internal static string SelectOwn {
            get {
                return ResourceManager.GetString("SelectOwn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select with User waypoints.
        /// </summary>
        internal static string SelectWithUserWP {
            get {
                return ResourceManager.GetString("SelectWithUserWP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        internal static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shapefiles.
        /// </summary>
        internal static string Shapefiles {
            get {
                return ResourceManager.GetString("Shapefiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shift.
        /// </summary>
        internal static string Shift {
            get {
                return ResourceManager.GetString("Shift", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shortcut assignment.
        /// </summary>
        internal static string ShortcutAssignment {
            get {
                return ResourceManager.GetString("ShortcutAssignment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show.
        /// </summary>
        internal static string Show {
            get {
                return ResourceManager.GetString("Show", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show additional waypoints.
        /// </summary>
        internal static string ShowAdditionalWaypoints {
            get {
                return ResourceManager.GetString("ShowAdditionalWaypoints", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show flagged only.
        /// </summary>
        internal static string ShowFlaggedOnly {
            get {
                return ResourceManager.GetString("ShowFlaggedOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show geocaches.
        /// </summary>
        internal static string ShowGeocaches {
            get {
                return ResourceManager.GetString("ShowGeocaches", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show selected only.
        /// </summary>
        internal static string ShowSelectedOnly {
            get {
                return ResourceManager.GetString("ShowSelectedOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to State.
        /// </summary>
        internal static string State {
            get {
                return ResourceManager.GetString("State", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        internal static string Status {
            get {
                return ResourceManager.GetString("Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to T.
        /// </summary>
        internal static string T {
            get {
                return ResourceManager.GetString("T", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Terr.
        /// </summary>
        internal static string Terr {
            get {
                return ResourceManager.GetString("Terr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Terrain.
        /// </summary>
        internal static string Terrain {
            get {
                return ResourceManager.GetString("Terrain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To.
        /// </summary>
        internal static string To {
            get {
                return ResourceManager.GetString("To", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type.
        /// </summary>
        internal static string Type {
            get {
                return ResourceManager.GetString("Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use the hints for description.
        /// </summary>
        internal static string UseHintsForDescription {
            get {
                return ResourceManager.GetString("UseHintsForDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use name and not geocache code.
        /// </summary>
        internal static string UseNameForGCCode {
            get {
                return ResourceManager.GetString("UseNameForGCCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use offline images.
        /// </summary>
        internal static string UseOfflineImages {
            get {
                return ResourceManager.GetString("UseOfflineImages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User name.
        /// </summary>
        internal static string UserName {
            get {
                return ResourceManager.GetString("UserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User names.
        /// </summary>
        internal static string UserNames {
            get {
                return ResourceManager.GetString("UserNames", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Waypoints.
        /// </summary>
        internal static string UserWaypoints {
            get {
                return ResourceManager.GetString("UserWaypoints", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Waypoints.
        /// </summary>
        internal static string Waypoints {
            get {
                return ResourceManager.GetString("Waypoints", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome.
        /// </summary>
        internal static string Welcome {
            get {
                return ResourceManager.GetString("Welcome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome to the Globalcaching Application (short GAPP).
        ///
        ///This wizard will guide you through the initial setup. Before you start, you might want to change the language:.
        /// </summary>
        internal static string WelcomeText {
            get {
                return ResourceManager.GetString("WelcomeText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Window.
        /// </summary>
        internal static string Window {
            get {
                return ResourceManager.GetString("Window", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Windows.
        /// </summary>
        internal static string Windows {
            get {
                return ResourceManager.GetString("Windows", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search within selection.
        /// </summary>
        internal static string WithinSelection {
            get {
                return ResourceManager.GetString("WithinSelection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        internal static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yours.
        /// </summary>
        internal static string Yours {
            get {
                return ResourceManager.GetString("Yours", resourceCulture);
            }
        }
    }
}
