//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GlobalcachingApplication.Plugins.OKAPI.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "12.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool UpgradeNeeded {
            get {
                return ((bool)(this["UpgradeNeeded"]));
            }
            set {
                this["UpgradeNeeded"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string ActiveSiteID {
            get {
                return ((string)(this["ActiveSiteID"]));
            }
            set {
                this["ActiveSiteID"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string SiteInfoGermanyUsername {
            get {
                return ((string)(this["SiteInfoGermanyUsername"]));
            }
            set {
                this["SiteInfoGermanyUsername"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string SiteInfoGermanyUserID {
            get {
                return ((string)(this["SiteInfoGermanyUserID"]));
            }
            set {
                this["SiteInfoGermanyUserID"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string SiteInfoNetherlandsUsername {
            get {
                return ((string)(this["SiteInfoNetherlandsUsername"]));
            }
            set {
                this["SiteInfoNetherlandsUsername"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string SiteInfoNetherlandsUserID {
            get {
                return ((string)(this["SiteInfoNetherlandsUserID"]));
            }
            set {
                this["SiteInfoNetherlandsUserID"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string SiteInfoPolandUsername {
            get {
                return ((string)(this["SiteInfoPolandUsername"]));
            }
            set {
                this["SiteInfoPolandUsername"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string SiteInfoPolandUserID {
            get {
                return ((string)(this["SiteInfoPolandUserID"]));
            }
            set {
                this["SiteInfoPolandUserID"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string SiteInfoUSAUsername {
            get {
                return ((string)(this["SiteInfoUSAUsername"]));
            }
            set {
                this["SiteInfoUSAUsername"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string SiteInfoUSAUserID {
            get {
                return ((string)(this["SiteInfoUSAUserID"]));
            }
            set {
                this["SiteInfoUSAUserID"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string SiteInfoUKUsername {
            get {
                return ((string)(this["SiteInfoUKUsername"]));
            }
            set {
                this["SiteInfoUKUsername"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string SiteInfoUKUserID {
            get {
                return ((string)(this["SiteInfoUKUserID"]));
            }
            set {
                this["SiteInfoUKUserID"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string SiteInfoGermanyToken {
            get {
                return ((string)(this["SiteInfoGermanyToken"]));
            }
            set {
                this["SiteInfoGermanyToken"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string SiteInfoGermanyTokenSecret {
            get {
                return ((string)(this["SiteInfoGermanyTokenSecret"]));
            }
            set {
                this["SiteInfoGermanyTokenSecret"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string SiteInfoNetherlandsToken {
            get {
                return ((string)(this["SiteInfoNetherlandsToken"]));
            }
            set {
                this["SiteInfoNetherlandsToken"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string SiteInfoNetherlandsTokenSecret {
            get {
                return ((string)(this["SiteInfoNetherlandsTokenSecret"]));
            }
            set {
                this["SiteInfoNetherlandsTokenSecret"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string SiteInfoPolandToken {
            get {
                return ((string)(this["SiteInfoPolandToken"]));
            }
            set {
                this["SiteInfoPolandToken"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string SiteInfoPolandTokenSecret {
            get {
                return ((string)(this["SiteInfoPolandTokenSecret"]));
            }
            set {
                this["SiteInfoPolandTokenSecret"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string SiteInfoUSAToken {
            get {
                return ((string)(this["SiteInfoUSAToken"]));
            }
            set {
                this["SiteInfoUSAToken"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string SiteInfoUSATokenSecret {
            get {
                return ((string)(this["SiteInfoUSATokenSecret"]));
            }
            set {
                this["SiteInfoUSATokenSecret"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string SiteInfoUKToken {
            get {
                return ((string)(this["SiteInfoUKToken"]));
            }
            set {
                this["SiteInfoUKToken"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string SiteInfoUKTokenSecret {
            get {
                return ((string)(this["SiteInfoUKTokenSecret"]));
            }
            set {
                this["SiteInfoUKTokenSecret"] = value;
            }
        }
    }
}
